### ISSUE TITLE
Facing 404 Error

### ISSUE THREAD

**Issue by arbazkiraak** [alienwithin/OWASP-mth3l3m3nt-framework#1]
![1111111111](https://cloud.githubusercontent.com/assets/13177578/17188872/a2d58a50-545c-11e6-8d2b-25c0f71d8e1e.PNG) For All Other Pages'.

Where As Main Page Work's Fine.

Followed the Exact Instruction Shown in Video .

Kali Linux 2.0

**Comment by alienwithin** [comment]
Try enabling mod rewrite seems to be a rewrite issue: 

a2enmod rewrite then restart apache

**Comment by arbazkiraak** [comment]
Hello , Thanks for you'r Reply,

 :  chmod -R 777 OWASP-mth3l3m3nt-framework And Restarted Apache Server.

Still Same Error ,

**Comment by alienwithin** [comment]
It isn't a permissions issue that would have shown on the homepage if it was : and don't put the whole framework on 0777 just the specified forlders for your safety :) 

in the path : **/etc/apache2/apache2.conf**  please ensure that the directives for the webroot are similar to below , more information is here: [Initial Webserver Configuration](https://github.com/alienwithin/OWASP-mth3l3m3nt-framework/wiki/WebServer-Configuration)

<Directory /var/www/>
    Options -Indexes +FollowSymLinks +Includes
    AllowOverride All
    Order allow,deny
    Allow from all
    Require all granted # This is required for apache 2.4.3 or higher if lower version remove this line
</Directory>

Since you are on kali : you can alternatively get the file here and replace urs with this.

[Apache 2 Config](https://github.com/alienwithin/OWASP-mth3l3m3nt-framework/blob/master/server-configs/apache2.conf)

in terminal as root do the commands below : 

**a2enmod rewrite
service apache2 restart**

**Comment by alienwithin** [comment]
Additionally check if the [.htaccess](https://github.com/alienwithin/OWASP-mth3l3m3nt-framework/blob/master/.htaccess) file exists in your folder.  If it does change the line : 

**#RewriteBase /**
to 

**RewriteBase /OWASP-mth3l3m3nt-framework-master**

If it doesn't exist download it and do the above steps. Please inform if it closes your issue.
